services:
  gitlab-server-service:
    image: gitlab/gitlab-ce:18.6.1-ce.0
    container_name: gitlab-local-server
    restart: always
    # environment:
      # GITLAB_OMNIBUS_CONFIG: |
      #  external_url 'http://gitlab.cluster.com:8080'
    ports:
      - '8080:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '1gb'
